name: Yunlong
title: Personal Website
url: https://algorithmx.github.io
description: Personal website of Yunlong.
destination: ./_site
repository: algorithmx/algorithmx.github.io
lsi: false
port: 4000
markdown: kramdown
future: true
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
permalink: pretty
#seo
tagline: Yunlong | Personal Website | Professional Portfolio | Projects | Blog
#paginate: 5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
